export type Theme = "dark" | "light" | "contrast";

export enum ThemeVarNames {
  // default colors
  Blue = "--blue",
  Yellow = "--yellow",
  Red = "--red",
  Green = "--green",
  Orange = "--orange",
  Brown = "--brown",
  Purple = "--purple",
  Grey = "--grey",

  PrimaryBg = "--rose-primary-bg",
  SecondaryBg = "--rose-secondary-bg",
  TertiaryBg = "--rose-tertiary-bg",
  PrimaryText = "--rose-primary-text",
  TertiaryText = "--rose-tertiary-text",
  SecondaryText = "--rose-secondary-text",
  Hover = "--rose-hover",
  HoverText = "--rose-hover-text",
  PrimaryBrand = "--rose-primary-brand",
  SecondaryBrand = "--rose-secondary-brand",
  Border = "--rose-border",
  Focus = "--rose-focus",
  ShadowFocus = "--rose-shadow-focus",
  Shadow = "--rose-shadow",
  Disabled = "--rose-disabled",
  DisabledLight = "--rose-disabled-light",
  DisabledDark = "--rose-disabled-dark",

  // buttons
  Action = "--rose-action",
  ActionDark = "--rose-action-dark",
  ActionContrast = "--rose-action-contrast",
  Error = "--rose-error",
  ErrorLight = "--rose-error-light",
  ErrorDark = "--rose-error-dark",
  ErrorContrast = "--rose-error-contrast",
  Warning = "--rose-warning",
  WarningLight = "--rose-warning-light",
  WarningDark = "--rose-warning-dark",
  Info = "--rose-info",
  InfoLight = "--rose-info-light",
  InfoDark = "--rose-info-dark",
  Success = "--rose-success",
  SuccessLight = "--rose-success-light",
  SuccessDark = "--rose-success-dark",

  // inputs
  InputPrimary = "--rose-input-primary",
  InputAlternative = "--rose-input-alternative",

  // charts
  Timeseries1 = "--rose-timeserie-1",
  Timeseries2 = "--rose-timeserie-2",
  Timeseries3 = "--rose-timeserie-3",
  Timeseries4 = "--rose-timeserie-4",
  Timeseries5 = "--rose-timeserie-5",
  Timeseries6 = "--rose-timeserie-6",
  Timeseries7 = "--rose-timeserie-7",
  Timeseries8 = "--rose-timeserie-8",
  Timeseries9 = "--rose-timeserie-9",
  TimeseriesNeutral = "--rose-timeseries-neutral",
  SharedAxis1 = "--rose-shared-axis-1",
  SharedAxis2 = "--rose-shared-axis-2",
  SharedAxis3 = "--rose-shared-axis-3",
  SharedAxis4 = "--rose-shared-axis-4",
  SharedAxis5 = "--rose-shared-axis-5",
}
